import { IAzkarOffset } from "./interface/IAzkarOffset";

export const azkarOffset:IAzkarOffset[]=[
    {
        titleId:18,
        zekr:[
            {
                zekrApi:4,
                zekrDB:4
            }
        ]
    },
    {
        titleId:27,
        zekr:[
            {
                zekrApi:0,
                zekrDB:2
            },
            {
                zekrApi:1,
                zekrDB:2
            },
            {
                zekrApi:3,
                zekrDB:4
            }
        ]
    },{
        titleId:31,
        zekr:[
            {
                zekrApi:7,
                zekrDB:3
            },
            {
                zekrApi:11,
                zekrDB:2
            }
        ]
    }
    ,{
        titleId:34,
        zekr:[
            {
                zekrApi:0,
                zekrDB:4
            },
        ]
    },{
        titleId:43,
        zekr:[
            {
                zekrApi:0,
                zekrDB:2
            }
        ]
    },{
        titleId:58,
        zekr:[
            {
                zekrApi:0,
                zekrDB:2
            }
        ]
    }
]